### ISSUE TITLE
Can't migrate: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by f1nnix** [modlinltd/django-advanced-filters#34]
Hi, thank you for building `django-advanced-filters`. Trying to set up as described in README. After running migrate, getting this error:

```
root@758956a011f8:/usr/src/myapp# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup

    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/easy_select2/__init__.py", line 7, in <module>
    from easy_select2.utils import (
  File "/usr/local/lib/python3.5/site-packages/easy_select2/utils.py", line 6, in <module>
    from easy_select2.widgets import Select2Mixin, Select2, Select2Multiple
  File "/usr/local/lib/python3.5/site-packages/easy_select2/widgets.py", line 16, in <module>
    static('easy_select2/js/easy_select2.js'),
  File "/usr/local/lib/python3.5/site-packages/django/templatetags/static.py", line 163, in static
    return StaticNode.handle_simple(path)
  File "/usr/local/lib/python3.5/site-packages/django/templatetags/static.py", line 112, in handle_simple
    if apps.is_installed('django.contrib.staticfiles'):
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 225, in is_installed
    self.check_apps_ready()
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Is Django 1.10+ supported?

FYI,

```
root@758956a011f8:/usr/src/myapp# django-admin --version
1.10.2
root@758956a011f8:/usr/src/myapp# python --version
Python 3.5.2```

Thank you.

**Comment by asfaltboy** [comment]
Hi @f1nnix and thank you for your interest in django-advanced-filters!

Unfortunately, we haven't got around to supporting Django 1.10, PRs are welcome :)
