### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by elcolie** [modlinltd/django-advanced-filters#65]
django==2.0.4
django-advanced-filters==1.0.7.1

```bash
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/sarit/.pyenv/versions/3.6.4/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/advanced_filters/models.py", line 16, in <module>
    class AdvancedFilter(models.Model):
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/advanced_filters/models.py", line 23, in AdvancedFilter
    related_name='created_advanced_filters', verbose_name=_('Created by'))
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

In Django2. `Model` needs explicit definition of `on_delete`.

**Comment by elcolie** [comment]
https://github.com/modlinltd/django-advanced-filters/pull/63
Sorry
